language: java
jdk: openjdk8
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull selenium/hub
  - docker pull selenium/node-chrome-debug
  - docker pull selenium/node-firefox-debug
  - docker-compose up -d

script:
  - mvn clean test
  - mvn allure:report

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/site/allure-maven-plugin
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master

after_script:
  - docker-compose down
