os: linux
dist: xenial
language: java
jdk: openjdk8
services:
  - docker

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

script:
  - mvn clean verify -Dprops.browser.and.version=firefox,85.0.1 -Dwdm.gitHubTokenName=deployment_to_github_pages -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN
  - mvn allure:report

deploy:
  strategy: git
  provider: pages
  cleanup: false
  local_dir: target/site/allure-maven-plugin
  github-token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
