language: java
jdk: openjdk8
sudo: required
services:
  - docker

before_install:
  - docker pull selenium/hub:3.141.59-xenon
  - docker pull selenium/node-chrome-debug
  - docker pull selenium/node-firefox-debug
  - docker-compose up

script: mvn clean verify

after_script:
  - docker-compose down
