language: java
jdk: openjdk8
sudo: required
services:
  - docker

before_install:
  - docker pull selenium/hub
  - docker pull selenium/node-chrome-debug
  - docker pull selenium/node-firefox-debug
  - docker-compose up -d

script:
  - mvn clean test
  - mvn allure:report

deploy:
  provider: pages
  skip_cleanup: false
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: main

after_script:
  - docker-compose down
