language: java
jdk: openjdk8
sudo: required
services:
  - docker

before_install:
  - docker pull selenium/hub
  - docker pull selenium/node-chrome-debug
  - docker pull selenium/node-firefox-debug
  - docker-compose up -d

script: mvn clean verify

after_script:
  - docker-compose down
