language: java
jdk: openjdk8
sudo: required
services:
  - docker

branches:
  only:
    - master

script:
  - mvn clean verify -Dprops.browser.and.version=firefox,73.0
  - mvn clean test
  - mvn allure:report

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/site/allure-maven-plugin
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
