version: '2'
services:
  firefox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 2
      NODE_MAX_SESSION: 2
    ports:
      - "9001:5900"

  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 2
      NODE_MAX_SESSION: 2
    ports:
      - "9002:5900"

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
